//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp. Do not edit.
//----------------------------------------------------------------------

#include "NFDRSInitConfig.h"





//--------
// Define the singleton object
//--------
NFDRSInitConfig NFDRSInitConfig::s_singleton;


NFDRSInitConfig::NFDRSInitConfig()
{
	m_schema[0] = "avgAnnualPrecip = float";
	m_schema[1] = "fuelModel = string";
	m_schema[2] = "gsi_opts = scope";
	m_schema[3] = "gsi_opts.fuelMoistureMax = int";
	m_schema[4] = "gsi_opts.fuelMoistureMin = int";
	m_schema[5] = "gsi_opts.gsiAveragingDays = int";
	m_schema[6] = "gsi_opts.gsiDayLenMax = int";
	m_schema[7] = "gsi_opts.gsiDayLenMin = int";
	m_schema[8] = "gsi_opts.gsiHerbGreenup = float";
	m_schema[9] = "gsi_opts.gsiMax = float";
	m_schema[10] = "gsi_opts.gsiNumPrecipDays = int";
	m_schema[11] = "gsi_opts.gsiRTPrecipMax = float";
	m_schema[12] = "gsi_opts.gsiRTPrecipMin = float";
	m_schema[13] = "gsi_opts.gsiTminMax = int";
	m_schema[14] = "gsi_opts.gsiTminMin = int";
	m_schema[15] = "gsi_opts.gsiUseVpdAvg = int";
	m_schema[16] = "gsi_opts.gsiVpdMax = int";
	m_schema[17] = "gsi_opts.gsiVpdMin = int";
	m_schema[18] = "herb_opts = scope";
	m_schema[19] = "herb_opts.fuelMoistureMax = int";
	m_schema[20] = "herb_opts.fuelMoistureMin = int";
	m_schema[21] = "herb_opts.gsiAveragingDays = int";
	m_schema[22] = "herb_opts.gsiDayLenMax = int";
	m_schema[23] = "herb_opts.gsiDayLenMin = int";
	m_schema[24] = "herb_opts.gsiHerbGreenup = float";
	m_schema[25] = "herb_opts.gsiMax = float";
	m_schema[26] = "herb_opts.gsiNumPrecipDays = int";
	m_schema[27] = "herb_opts.gsiRTPrecipMax = float";
	m_schema[28] = "herb_opts.gsiRTPrecipMin = float";
	m_schema[29] = "herb_opts.gsiTminMax = int";
	m_schema[30] = "herb_opts.gsiTminMin = int";
	m_schema[31] = "herb_opts.gsiUseVpdAvg = int";
	m_schema[32] = "herb_opts.gsiVpdMax = int";
	m_schema[33] = "herb_opts.gsiVpdMin = int";
	m_schema[34] = "isAnnuals = int";
	m_schema[35] = "isHumid = int";
	m_schema[36] = "kbdiThreshold = int";
	m_schema[37] = "latitude = float";
	m_schema[38] = "liveFuelMoisture = scope";
	m_schema[39] = "liveFuelMoisture.defaults = scope";
	m_schema[40] = "liveFuelMoisture.defaults.fuelMoistureMax = int";
	m_schema[41] = "liveFuelMoisture.defaults.fuelMoistureMin = int";
	m_schema[42] = "liveFuelMoisture.defaults.gsiAveragingDays = int";
	m_schema[43] = "liveFuelMoisture.defaults.gsiDayLenMax = int";
	m_schema[44] = "liveFuelMoisture.defaults.gsiDayLenMin = int";
	m_schema[45] = "liveFuelMoisture.defaults.gsiHerbGreenup = float";
	m_schema[46] = "liveFuelMoisture.defaults.gsiMax = float";
	m_schema[47] = "liveFuelMoisture.defaults.gsiNumPrecipDays = int";
	m_schema[48] = "liveFuelMoisture.defaults.gsiRTPrecipMax = float";
	m_schema[49] = "liveFuelMoisture.defaults.gsiRTPrecipMin = float";
	m_schema[50] = "liveFuelMoisture.defaults.gsiTminMax = int";
	m_schema[51] = "liveFuelMoisture.defaults.gsiTminMin = int";
	m_schema[52] = "liveFuelMoisture.defaults.gsiUseVpdAvg = int";
	m_schema[53] = "liveFuelMoisture.defaults.gsiVpdMax = int";
	m_schema[54] = "liveFuelMoisture.defaults.gsiVpdMin = int";
	m_schema[55] = "maxSC = int";
	m_schema[56] = "obsHour = int";
	m_schema[57] = "slopeClass = int";
	m_schema[58] = "startKBDI = int";
	m_schema[59] = "timeZoneOffset = int";
	m_schema[60] = "useCure = int";
	m_schema[61] = "useLoadTransfer = int";
	m_schema[62] = "woody_opts = scope";
	m_schema[63] = "woody_opts.fuelMoistureMax = int";
	m_schema[64] = "woody_opts.fuelMoistureMin = int";
	m_schema[65] = "woody_opts.gsiAveragingDays = int";
	m_schema[66] = "woody_opts.gsiDayLenMax = int";
	m_schema[67] = "woody_opts.gsiDayLenMin = int";
	m_schema[68] = "woody_opts.gsiHerbGreenup = float";
	m_schema[69] = "woody_opts.gsiMax = float";
	m_schema[70] = "woody_opts.gsiNumPrecipDays = int";
	m_schema[71] = "woody_opts.gsiRTPrecipMax = float";
	m_schema[72] = "woody_opts.gsiRTPrecipMin = float";
	m_schema[73] = "woody_opts.gsiTminMax = int";
	m_schema[74] = "woody_opts.gsiTminMin = int";
	m_schema[75] = "woody_opts.gsiUseVpdAvg = int";
	m_schema[76] = "woody_opts.gsiVpdMax = int";
	m_schema[77] = "woody_opts.gsiVpdMin = int";
	m_schema[78] = 0;

	m_str << "#Sample NFDRS2016 initialization file\n";
	m_str << "#contains all parameters to initialize an NFSDRS20";
	m_str << "16 object for computation\n";
	m_str << "#used by config2cpp as:\n";
	m_str << "#config2cpp -cfg NFDRSInitSample.txt -class NFDRSI";
	m_str << "nitConfig -singleton\n";
	m_str << "#\n";
	m_str << "#latitude decimal degrees\n";
	m_str << "latitude = \"47.01\";\n";
	m_str << "#NFDRS2016 fuel model (one of V, W, X, Y, Z)\n";
	m_str << "fuelModel = \"Y\";\n";
	m_str << "#standard NFDRS Slope Class (1 = 0.25%, 2 = 26-40%";
	m_str << ", 3 = 41 - 55%, 4 = 56 - 75%, 5 = 76%+)\n";
	m_str << "slopeClass = \"1\";\n";
	m_str << "#average annual precipitation (inches)\n";
	m_str << "avgAnnualPrecip = \"13.4\";\n";
	m_str << "#load transfer flag, should always be \"1\"\n";
	m_str << "useLoadTransfer = \"1\";\n";
	m_str << "#curing flag, should always be \"1\"\n";
	m_str << "useCure = \"1\";\n";
	m_str << "#annuals flag, 1 = herbs are annuals, 0 = perennia";
	m_str << "l\n";
	m_str << "isAnnuals = \"1\";\n";
	m_str << "#threshold KBDI value, minimum value to have KBDI ";
	m_str << "modify NFDRS Index calculation\n";
	m_str << "kbdiThreshold = \"100\";\n";
	m_str << "# initial KBDI value on Init\n";
	m_str << "startKBDI = \"100\";\n";
	m_str << "# flag to indicate Humid climate\n";
	m_str << "isHumid = \"0\";\n";
	m_str << "# hour when daily observations are reported and GS";
	m_str << "I/Live fuel moistures updated\n";
	m_str << "obsHour = \"13\";\n";
	m_str << "# timeZone offset from UTC, absolutely necessary i";
	m_str << "f FW21 data is Zulu time\n";
	m_str << "timeZoneOffset = \"-6\";\n";
	m_str << "#for maxSC, any positive value other than zero (0)";
	m_str << " will override fuel model default maxSC\n";
	m_str << "maxSC = \"0\";\n";
	m_str << "#\n";
	m_str << "#GSI and Live Fuel Moistures\n";
	m_str << "#\n";
	m_str << "liveFuelMoisture.defaults {\n";
	m_str << "\tgsiMax = \"1.0\";\n";
	m_str << "\tgsiHerbGreenup = \"0.5\";\n";
	m_str << "\tgsiTminMin = \"-2\";\n";
	m_str << "\tgsiTminMax = \"5\";\n";
	m_str << "\tgsiVpdMin = \"900\";\n";
	m_str << "\tgsiVpdMax = \"4100\";\n";
	m_str << "\tgsiDayLenMin = \"36000\";\n";
	m_str << "\tgsiDayLenMax = \"39600\";\n";
	m_str << "\tgsiUseVpdAvg = \"0\";\n";
	m_str << "\tgsiAveragingDays = \"21\";\n";
	m_str << "\tgsiNumPrecipDays = \"30\";\n";
	m_str << "\tgsiRTPrecipMin = \"0.5\";\n";
	m_str << "\tgsiRTPrecipMax = \"1.5\";\n";
	m_str << "\tfuelMoistureMax = \"100\";\n";
	m_str << "\tfuelMoistureMin = \"0\";\n";
	m_str << "}\n";
	m_str << "#set any GSI specific options here\n";
	m_str << "gsi_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\n";
	m_str << "}\n";
	m_str << "#set any Herb LFM specific options here\n";
	m_str << "herb_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\tfuelMoistureMax = \"250\";\n";
	m_str << "\tfuelMoistureMin = \"30\";\n";
	m_str << "}\n";
	m_str << "\n";
	m_str << "#set any Woody LFM specific options here\n";
	m_str << "woody_opts {\n";
	m_str << "\t@copyFrom \"liveFuelMoisture.defaults\";\n";
	m_str << "\tfuelMoistureMax = \"200\";\n";
	m_str << "\tfuelMoistureMin = \"50\";\n";
	m_str << "}";
}





NFDRSInitConfig::~NFDRSInitConfig()
{
	// Nothing to do
}


