//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fireplus.rc
//
#define IDSELECTALL                     3
#define IDC_BATCH_SELECTALL             3
#define IDFILTER                        3
#define IDC_SHAPEFILE                   3
#define IDDESELECTALL                   4
#define IDC_BATCH_DESELECTALL           4
#define IDFILTER2                       5
#define IDC_BATCH_SORT                  6
#define IDD_ABOUTBOX                    100
#define IDD_FIREPLUS_FORM               101
#define IDD_PROPPAGE_LINEGRAPH          102
#define IDD_PROPPAGE_LINEGRAPH2         102
#define IDR_DPID                        102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDC_NFDRS                       103
#define IDD_DIALOGBAR_CANDIDATES        103
#define IDD_QUICKBATCHGRAPHPAGE         104
#define ID_INDICATOR_TERM_DAY_PROMPT    104
#define IDC_NFDRS2                      105
#define ID_INDICATOR_TERM_DAY           105
#define IDD_FIREPROPPAGE                106
#define IDC_NFDRS3                      106
#define ID_INDICATOR_TERM_PROB_PROMPT   106
#define IDR_HTML_HOURLYEVENTLOCATORDLG  107
#define ID_INDICATOR_TERM_PROB          107
#define IDD_PROPPAGE_LFI_GENERAL        107
#define IDR_HTML_TERMDATESDIALOG        108
#define IDD_NFDRS2016WXVIEW             109
#define IDR_WEATHERVIEW_TMPL            110
#define IDR_NFDRS2016WXVIEW_TMPL        111
#define IDR_MAINFRAME                   128
#define IDR_FIREPLTYPE                  129
#define IDD_CLIMDIALOG                  130
#define IDR_TEXTTYPE                    130
#define IDD_FORMVIEW                    131
#define IDD_CLIMATE_FORM                131
#define IDB_BITMAP1                     136
#define IDD_GWCLIMGRID                  139
#define IDR_CLIMTYPE                    141
#define IDD_SIGSDIALOG                  142
#define IDD_EDITSIGDIALOG               144
#define IDD_WEIGHTSDIALOG               145
#define IDR_SPLITGRAPHTYPE              147
#define IDD_OVERLAYDIALOG               151
#define IDD_GRAPHPRINTDIALOG            156
#define IDD_PPDIALOG                    160
#define IDD_SEVERITYDIALOG              162
#define IDD_PANALYSISDIALOG             164
#define IDD_FIREDIALOG                  168
#define IDD_RUN_RESTORE_DIALOG          168
#define IDD_RECCOUNTERDIALOG            171
#define IDD_POCKETCARDDIALOG            174
#define IDR_POCKETCARDTYPE              184
#define IDD_LISTINGDIALOG               186
#define IDD_WDDIALOG                    187
#define IDD_STATIONDIALOG               189
#define IDD_EDITSTATIONDIALOG           191
#define IDD_PROPPAGE_GENERAL            192
#define IDD_PROPPAGE_BARGRAPH           193
#define IDD_PROPPAGE_IMPORT             194
#define IDD_PROPPAGE_GRAPH_AUTOSAVE     194
#define IDD_CAUSEPROPPAGE               195
#define ID_APP_NASF                     197
#define IDD_IMPORTDIALOG                202
#define IDD_YEARSPAGE                   203
#define IDR_FIRESUMMENU                 204
#define IDD_FIREANALYSISDIALOG          205
#define IDD_LOGITDIALOG                 207
#define IDR_FIRESTATMENU                208
#define IDD_PROPPAGE_FIRES              208
#define IDR_CUMULATIVE                  209
#define IDD_AGENCYDIALOG                211
#define IDD_NEWAGENCYDIALOG             212
#define IDD_REGIONSDIALOG               213
#define IDD_NEWREGDIALOG                214
#define IDD_NEWUNITDIALOG               215
#define IDD_UNITSDIALOG                 216
#define IDD_SUBUNITSDIALOG              217
#define IDD_NEWSUBUNITDIALOG            218
#define IDD_CUSTOMFIREDIALOG            219
#define IDD_PROPPAGE_LGRAPH             220
#define IDD_RERAPDIALOG                 223
#define IDD_RERAPVARDIALOG              226
#define IDD_FDDIALOG                    231
#define IDD_TEXTDIALOG                  233
#define IDB_BITMAPGY                    236
#define IDB_BITMAPRY                    237
#define IDB_BITMAPY                     238
#define IDD_PCBKGNDDIALOG               239
#define IDB_BITMAPSGY                   240
#define IDB_BITMAPSRY                   241
#define IDB_BITMAPSY                    242
#define IDD_FIRESELDIALOG               243
#define IDD_NOWXDIALOG                  245
#define IDD_EVENTLOCATORDIALOG          246
#define IDD_IMPORTDONEDIALOG            248
#define IDD_COMPACTDIALOG               249
#define IDD_RICHDIALOG                  250
#define IDR_PRECIPGRAPHTYPE             251
#define IDD_DPFORM                      251
#define IDS_GRAPHICSFILEFILTER          252
#define IDD_PROGRESS_DIALOG             252
#define IDD_DPDIALOG                    254
#define IDD_FORCASTDIALOG               256
#define IDD_FORECASTOPTIONS             258
#define IDD_FORECASTGRAPHSDIALOG        260
#define IDD_DIURNALDIALOG               262
#define IDR_DIURNALMENU                 263
#define IDD_WTHRPRINTDIALOG             264
#define IDD_DELRECSDIALOG               284
#define IDD_WXSAVEDIALOG                286
#define IDR_SORTMENU                    287
#define IDD_FIRESFILTERDIALOG           288
#define IDD_FARSITEDIALOG               289
#define IDD_FIREEXPORTDIALOG            291
#define IDD_PROPPAGE_FX                 292
#define IDD_DIURNALFORM                 293
#define IDB_BITMAP2                     306
#define IDD_MERGEDIALOG                 307
#define IDD_COUNTERDIALOG               311
#define IDR_MERGEDGRAPH                 315
#define IDB_BITMAPMERGELAYOUT           317
#define IDD_USER_IMPORT_DIALOG          318
#define IDD_USERVARS_DIALOG             319
#define IDD_USERBROWSEDIALOG            321
#define IDD_PROPPAGE_RHEADER            327
#define IDD_RUNLOADDIALOG               328
#define IDD_PROPPAGE_DELIMITER          329
#define IDR_MENU1                       329
#define IDR_BATCHOUTPUT                 329
#define IDD_BATCH_CREATE_DIALOG         330
#define IDR_POCKETCARDTYPE1             330
#define IDD_BATCHCONFIRMDIALOG          331
#define IDD_BATCH_MANAGE_DIALOG         332
#define IDD_BATCH_EDIT_DIALOG           333
#define IDR_WINDROSETYPE                333
#define IDD_BATCHEDITCONFIRMDIALOG      334
#define IDD_BATCHDELETECONFIRMDIALOG    335
#define IDD_PROPPAGE_GRAPH_AUTOSAVE1    336
#define IDD_PROPPAGE_BATCH_AUTOSAVE     336
#define IDD_BATCHTABVIEW                337
#define IDD_RUN_MAINTENANCE_DIALOG      338
#define IDD_PROPPAGE_BATCH_GENERAL      339
#define IDD_BATCHPURGEDIALOG            340
#define IDD_RUNSAVEPROMPTDIALOG         341
#define IDD_QUICKBATCHDIALOG            345
#define IDB_BITMAPTREE                  346
#define IDD_RICHCTRLVIEW                346
#define IDB_BITMAPTREESELECT            347
#define IDD_WORKINGSETDIALOG            351
#define IDD_GRAPHSAVEDIALOG             353
#define IDD_WINDROSEDIALOG              354
#define IDR_MENU2                       355
#define IDD_FIRESHAPEFILEEXPORTDIALOG   355
#define IDD_STATION_EXPORT_DIALOG       356
#define IDD_GWIDIALOG                   357
#define IDB_BITMAP3                     358
#define IDD_GFIDIALOG                   358
#define IDB_BITMAP4                     359
#define IDD_SEL_STATION_DIALOG          359
#define IDB_BITMAP5                     360
#define IDD_NELSON_DIALOG               360
#define IDB_BITMAP6                     361
#define IDD_DIALOGFRISK                 362
#define IDD_BATCHDELETECONFIRMDIALOG1   363
#define IDD_UPGRADEDIALOG               363
#define IDD_QUICK_FIRE_OPTIONS          364
#define IDD_CUSTOMINITSDIALOG           365
#define IDD_CUSTOMINITDELETECONFIRMDIALOG 366
#define IDD_CUSTOMINIT_CREATE_DIALOG    367
#define IDD_CUSTOMINIT_EDIT_DIALOG      368
#define IDD_HOURLYEVENTLOCATORDIALOG    369
#define IDD_RUN_MAINTENANCE_MANUAL_DLG  370
#define IDD_LFIDIALOG                   372
#define IDD_TERM_DIALOG                 374
#define IDD_TERM_DATES_DIALOG           375
#define IDR_TERMMENU                    376
#define IDR_EVENTLOCATORTYPE            377
#define IDD_ADD_TO_TERM_DIALOG          377
#define IDD_TERM_PROBABILIATIES_DIALOG  378
#define IDD_FIRESVIEW                   379
#define IDD_WEATHERVIEW                 380
#define IDD_DIALOG_SELSIGSTATION        382
#define IDD_SOW_THRESHOLDS_DLG          383
#define IDD_DIALOG_SOW_WETFLAG_OPTIONS  384
#define IDR_FIRESVIEW_TMPL              385
#define IDD_CANDIDATESVIEW              386
#define IDD_PROPPAGE_LFI_HERB           387
#define IDD_PROPPAGE_LFI_WOODY          388
#define IDR_MENU3                       389
#define IDR_WEATHERVIEW_TMPL1           395
#define IDD_TERM_EXPORT_DIALOG          396
#define IDR_VARSORT                     397
#define IDD_IMPORT_WRCC_DIALOG          398
#define IDD_FIRESTATCAUSE_DIALOG        399
#define IDD_FIREDOICAUSE_DIALOG         400
#define IDD_FIRECAUSEFILTERDIALOG       401
#define IDD_SNOWFLAG_DIALOG             411
#define IDD_DIALOG_FILL_SNOWFLAG        414
#define IDD_DIALOG_SET_DAILY_OBS        416
#define IDB_BITMAP7                     418
#define IDB_BITMAP8                     419
#define IDB_BITMAP_FFP5                 421
#define IDD_DIALOG_FW21_EXPORT          427
#define IDC_DBNAME                      1005
#define IDC_SIGSTATION                  1006
#define IDC_SYEAR                       1007
#define IDC_EYEAR                       1008
#define IDC_SPIN1                       1009
#define IDC_SPIN2                       1010
#define IDC_SMONTH                      1011
#define IDC_EMONTH                      1012
#define IDC_SDAY                        1013
#define IDC_EDAY                        1014
#define IDC_SPIN3                       1015
#define IDC_SPIN4                       1016
#define IDC_PERIOD                      1017
#define IDC_SPIN5                       1018
#define IDC_DESCRIPTION                 1020
#define IDC_CHECK1                      1021
#define IDC_N                           1021
#define IDC_ENABLEALTERNATE             1021
#define IDC_YTDBUTTON                   1021
#define IDC_HEADERS                     1021
#define IDC_TYPE_11                     1021
#define IDC_REPORTHEADER                1021
#define IDC_WTR3CHECK                   1021
#define IDC_CONDITIONAL                 1021
#define IDC_CHECKSPACE                  1021
#define IDC_CHECK_DIURNAL               1021
#define IDC_CHECK_MONTHLY_WINDS         1021
#define IDC_CHECK_ALLSTATIONS           1021
#define IDC_DISABLE_RUN_SAVING          1021
#define IDC_CHECK_SHOWALL               1021
#define IDC_CHECK_FIRE_DAY              1021
#define IDC_CHECK_HUMID_V               1021
#define IDC_CHECK_GUSTS                 1021
#define IDC_CHECK_USE_RTPRECIP          1021
#define IDC_CHECK2                      1022
#define IDC_E                           1022
#define IDC_PAGENUMS                    1022
#define IDC_TYPE_12                     1022
#define IDC_COLUMNHEADER                1022
#define IDC_WTR4CHECK                   1022
#define IDC_CLOSEFORECAST               1022
#define IDC_CHECKCOMMA                  1022
#define IDC_NWCGSTANDARD                1022
#define IDC_CHECK_GENWINDROSE           1022
#define IDC_CHECK_HUMID_W               1022
#define IDC_CHECK_DAILY_EXTREMES        1022
#define IDC_CHECK3                      1023
#define IDC_S                           1023
#define IDC_RECNUMS                     1023
#define IDC_TYPE_13                     1023
#define IDC_DATESTAMP                   1023
#define IDC_WNDCHECK                    1023
#define IDC_CHECKTAB                    1023
#define IDC_CHECK_LARGE_FIRE_DAY        1023
#define IDC_CHECK_HUMID_X               1023
#define IDC_LIST1                       1024
#define IDC_CHECK6                      1024
#define IDC_SE                          1024
#define IDC_TYPE_22                     1024
#define IDC_CHECKSEMICOLON              1024
#define IDC_CHECK_HUMID_Y               1024
#define IDC_CHECK7                      1025
#define IDC_SW                          1025
#define IDC_TYPE_23                     1025
#define IDC_CHECK_HUMID_V2              1025
#define IDC_CHECK_HUMID_Z               1025
#define IDC_CHECK8                      1026
#define IDC_NW                          1026
#define IDC_TYPE_48                     1026
#define IDC_CHECK9                      1027
#define IDC_TYPE_49                     1027
#define IDC_CHECK10                     1028
#define IDC_CHECK11                     1036
#define IDC_DATATBLCTRL1                1036
#define IDC_CHECK12                     1037
#define IDC_DATATBLCTRL2                1037
#define IDC_CHECK13                     1038
#define IDC_BUTTON1                     1038
#define IDC_CHECK14                     1039
#define IDC_CUSTOM1                     1039
#define IDC_AVGSAPPLY                   1039
#define IDC_GRID                        1039
#define IDC_GRID1                       1039
#define IDC_CHECK15                     1040
#define IDC_COMBO1                      1040
#define IDC_CHECK16                     1041
#define IDC_METADATA                    1041
#define IDC_GRID2                       1041
#define IDC_CHECK17                     1042
#define IDC_BUTTON2                     1042
#define IDC_RUNCLIMATOLOGY              1042
#define IDC_SIGSEDIT                    1042
#define IDC_MOVELEFT                    1042
#define IDC_CHECK18                     1043
#define IDC_CLEARALL                    1043
#define IDC_CHECK19                     1044
#define IDC_NFDRS88                     1044
#define IDC_CHECK20                     1045
#define IDC_NFDRS78                     1045
#define IDC_CHECK21                     1046
#define IDC_SIGSDELETE                  1046
#define IDC_CHECK22                     1047
#define IDC_SIGSHELP                    1047
#define IDC_CHECK23                     1048
#define IDC_SIGSTABLE                   1048
#define IDC_CHECK24                     1049
#define IDC_SIGSNEW                     1049
#define IDC_CHECK25                     1050
#define IDC_SIGNAME                     1050
#define IDC_CHECK26                     1051
#define IDC_SIGDESCRIPTION              1051
#define IDC_CHECK27                     1052
#define IDC_LIST2                       1052
#define IDC_CHECK28                     1053
#define IDC_CHECK29                     1054
#define IDC_CHECK30                     1055
#define IDC_MOVERIGHT                   1055
#define IDC_CHECK31                     1056
#define IDC_WEIGHTS                     1056
#define IDC_CHECK32                     1057
#define IDC_WEIGHTS2                    1057
#define IDC_EXPORT_SIG                  1057
#define IDC_CHECK33                     1058
#define IDC_APPLY                       1058
#define IDC_CHECK34                     1059
#define IDC_DARKBLUE                    1059
#define IDC_CHECK35                     1060
#define IDC_BLUE                        1060
#define IDC_CPTICS                      1060
#define IDC_CHECK36                     1061
#define IDC_LIGHTBLUE                   1061
#define IDC_EDIT1                       1061
#define IDC_CHECK37                     1062
#define IDC_DARKGREEN                   1062
#define IDC_RADIO1                      1062
#define IDC_CHECK38                     1063
#define IDC_CYAN                        1063
#define IDC_RADIO2                      1063
#define IDC_CHECK39                     1064
#define IDC_LIGHTGREEN                  1064
#define IDC_HLINES                      1064
#define IDC_CHECK40                     1065
#define IDC_DARKRED                     1065
#define IDC_VLINES                      1065
#define IDC_CHECK41                     1066
#define IDC_LIGHTRED                    1066
#define IDC_RANGETICS                   1066
#define IDC_CHECK42                     1067
#define IDC_MAGENTA                     1067
#define IDC_CHECK43                     1068
#define IDC_DARKMAGENTA                 1068
#define IDC_VLINESTYLE                  1068
#define IDC_CHECK44                     1069
#define IDC_BROWN                       1069
#define IDC_HLINESTYLE                  1069
#define IDC_CHECK45                     1070
#define IDC_YELLOW                      1070
#define IDC_CHECK46                     1071
#define IDC_CHECK47                     1072
#define IDC_CHECK48                     1073
#define IDC_CHECK49                     1074
#define IDC_AVGCOLOR                    1074
#define IDC_CHECK50                     1075
#define IDC_MINSCOLOR                   1075
#define IDC_CHECK51                     1076
#define IDC_MAXSCOLOR                   1076
#define IDC_CHECK52                     1077
#define IDC_GDISABLE                    1077
#define IDC_CP1COLOR                    1077
#define IDC_CHECK53                     1078
#define IDC_PDISABLE                    1078
#define IDC_CP2COLOR                    1078
#define IDC_CHECK54                     1079
#define IDC_CHECK55                     1080
#define IDC_PROPERTIES                  1084
#define IDC_PRINTER                     1085
#define IDC_GLEFT                       1090
#define IDC_GRIGHT                      1091
#define IDC_GWIDTH                      1091
#define IDC_GTOP                        1092
#define IDC_GHEIGHT                     1092
#define IDC_GBOTTOM                     1093
#define IDC_GSAVE                       1093
#define IDC_PLEFT                       1094
#define IDC_PWIDTH                      1094
#define IDC_PVNUMERIC1                  1094
#define IDC_PRIGHT                      1095
#define IDC_PHEIGHT                     1095
#define IDC_COMBO2                      1095
#define IDC_RH                          1095
#define IDC_ELEVATION                   1095
#define IDC_MINSWIDTH                   1095
#define IDC_PVNUMERIC2                  1095
#define IDC_WORKINGSET                  1095
#define IDC_PTOP                        1096
#define IDC_PSAVE                       1096
#define IDC_COMBO3                      1096
#define IDC_TEMP                        1096
#define IDC_SITE                        1096
#define IDC_MAXSWIDTH                   1096
#define IDC_FUNIT                       1096
#define IDC_HERB                        1096
#define IDC_PBOTTOM                     1097
#define IDC_LIVEFM                      1097
#define IDC_CP1WIDTH                    1097
#define IDC_LUNIT                       1097
#define IDC_SHRUB                       1097
#define IDC_EDIT2                       1098
#define IDC_CP2WIDTH                    1098
#define IDC_FSUBUNITS                   1098
#define IDC_WINDS                       1098
#define IDC_GREATERTHANCP               1099
#define IDC_LSUBUNITS                   1099
#define IDC_EDITYVAL                    1099
#define IDC_LESSTHANCP                  1100
#define IDC_YEAR                        1100
#define IDC_EDITGYVAL                   1100
#define IDC_EDIT3                       1101
#define IDC_MONTH                       1102
#define IDC_INDEX                       1103
#define IDC_BITMAP                      1104
#define IDC_DAY                         1104
#define IDC_FUELMODELNAME               1105
#define IDC_YEAR1                       1106
#define IDC_FFNUM                       1106
#define IDC_YEAR2                       1107
#define IDC_LFNUM                       1107
#define IDC_FIRESTABLE                  1108
#define IDC_FACRES                      1108
#define IDC_LACRES                      1109
#define IDC_CP                          1109
#define IDC_PETEXT                      1110
#define IDC_CAUSE                       1110
#define IDC_WINDSPEED                   1111
#define IDC_FNAME                       1111
#define IDC_AREA                        1112
#define IDC_LNAME                       1112
#define IDC_LINE1                       1113
#define IDC_LINE2                       1114
#define IDC_LINE3                       1115
#define IDC_REMOVEALL                   1117
#define IDC_SELECTALL                   1118
#define IDC_STATIONNEW                  1119
#define IDC_STATIONEDIT                 1120
#define IDC_STATIONDELETE               1121
#define IDC_STATIONID                   1122
#define IDC_STATIONEXPORT               1122
#define IDC_NAME                        1123
#define IDC_LATITUDE                    1125
#define IDC_LONGITUDE                   1126
#define IDC_ASPECT                      1127
#define IDC_STATE                       1128
#define IDC_COUNTY                      1129
#define IDC_COUNTYBOX                   1129
#define IDC_AGENCY                      1130
#define IDC_HERBANNUAL                  1131
#define IDC_DECIDUOUS                   1132
#define IDC_FM1EQ10                     1133
#define IDC_USESTICK                    1134
#define IDC_USEDORMANT                  1135
#define IDC_NFDRSFM                     1136
#define IDC_REGION                      1137
#define IDC_SLOPEPOSITION               1138
#define IDC_SLOPECLASS                  1139
#define IDC_CLIMATECLASS                1140
#define IDC_PRECIP                      1141
#define IDC_FM1000                      1142
#define IDC_GREENHERB                   1143
#define IDC_GREENSHRUB                  1144
#define IDC_KBDI                        1145
#define IDC_FREEZEDATE                  1146
#define IDC_GREENUPDATE                 1147
#define IDC_USE88                       1148
#define IDC_STARTUPDAY                  1148
#define IDC_OBSUNIT                     1149
#define IDC_STNTYPE                     1150
#define IDC_DORMANTDATE                 1151
#define IDC_FIRESBUTTON                 1152
#define IDC_CP2                         1158
#define IDC_MAXS                        1160
#define IDC_CP1                         1161
#define IDC_AVGWIDTH                    1162
#define IDC_MINS                        1163
#define IDC_SETDEFBUTTON                1164
#define IDC_APPLYTOALL                  1165
#define IDC_MYOK                        1166
#define IDC_MYCANCEL                    1167
#define IDC_STATBARS                    1168
#define IDC_LINEGRAPH                   1169
#define IDC_SUBUNITSLIST                1170
#define IDC_REGIONSLIST                 1171
#define IDC_UNITSLIST                   1172
#define IDC_OVERLAYYEARS                1173
#define IDC_FPL                         1174
#define IDC_RAW                         1175
#define IDC_FW9                         1176
#define IDC_FWX                         1177
#define IDC_PCHAFWX                     1178
#define IDC_FWSTXT                      1178
#define IDC_CAUSES                      1179
#define IDC_GWI                         1179
#define IDC_USEALL                      1180
#define IDC_WFMI                        1180
#define IDC_USESELECTED                 1181
#define IDC_GENERICFIRE                 1181
#define IDC_WRCCRAWS                    1182
#define IDC_RADIO3                      1185
#define IDC_RADIO4                      1186
#define IDC_RADIO5                      1187
#define IDC_RADIO6                      1188
#define IDC_RADIO7                      1189
#define IDC_CHECK_LFD                   1190
#define IDC_CHECK_MFD                   1191
#define IDC_RADIO_ALL                   1192
#define IDC_RADIO_LIGHTNING             1193
#define IDC_RADIO_HUMAN                 1194
#define IDC_PVNUMERIC_LFD               1195
#define IDC_PVNUMERIC_MFD               1196
#define IDC_CHECK_FD                    1197
#define IDC_DELBUTTON                   1200
#define IDC_REGBUTTON                   1201
#define IDC_AGENCIES                    1202
#define IDC_NEWBUTTON                   1203
#define IDC_EDITBUTTON                  1204
#define IDC_UNITSBUTTON                 1205
#define IDC_REGIONS                     1206
#define IDC_CODE                        1207
#define IDC_UNITS                       1209
#define IDC_SUBUNITSBUTTON              1210
#define IDC_SUBUNITS                    1211
#define IDC_USEREG                      1216
#define IDC_USEUNIT                     1217
#define IDC_USESUBUNIT                  1218
#define IDC_REGS                        1219
#define IDC_FREG                        1220
#define IDC_LREG                        1221
#define IDC_YFN                         1222
#define IDC_YRFN                        1223
#define IDC_YRUFN                       1224
#define IDC_YRUSFN                      1225
#define IDC_NONE                        1226
#define IDC_LONG                        1232
#define IDC_LAT                         1233
#define IDC_MED1                        1240
#define IDC_LOW                         1241
#define IDC_MED2                        1242
#define IDC_HIGH1                       1243
#define IDC_HIGH2                       1244
#define IDC_EXTREME1                    1245
#define IDC_LM1                         1246
#define IDC_LOWPERCENT                  1247
#define IDC_MEDIUMPERCENT               1248
#define IDC_HIGHPERCENT                 1249
#define IDC_EXTREMEPERCENT              1250
#define IDC_LM2                         1251
#define IDC_LOWOBS                      1255
#define IDC_MEDIUMOBS                   1256
#define IDC_HIGHOBS                     1257
#define IDC_EXTREMEOBS                  1258
#define IDC_LOW1HR                      1259
#define IDC_W                           1260
#define IDC_NE                          1261
#define IDC_FREQS                       1262
#define IDC_MED1HR                      1263
#define IDC_PROGRESS_TEXT               1263
#define IDC_PROGRESS_BAR                1264
#define IDC_HIGH1HR                     1264
#define IDC_EXT1HR                      1265
#define IDC_PROGRESS_COUNTTEXT          1265
#define IDC_PROGRESS_COUNT_TEXT         1265
#define IDC_LOW10HR                     1266
#define IDC_MED10HR                     1267
#define IDC_HIGH10HR                    1268
#define IDC_EXT10HR                     1269
#define IDC_LOW100HR                    1270
#define IDC_MED100HR                    1271
#define IDC_HIGH100HR                   1272
#define IDC_EXT100HR                    1273
#define IDC_LOWHERB                     1274
#define IDC_MEDHERB                     1275
#define IDC_HIGHHERB                    1276
#define IDC_EXTHERB                     1277
#define IDC_LOWWOODY                    1278
#define IDC_MEDWOODY                    1279
#define IDC_HIGHWOODY                   1280
#define IDC_EXTWOODY                    1281
#define IDC_LOW20                       1282
#define IDC_MED20                       1283
#define IDC_HIGH20                      1284
#define IDC_EXT20                       1285
#define IDC_LOW1000HR                   1286
#define IDC_MED1000HR                   1287
#define IDC_HIGH1000HR                  1288
#define IDC_EXT1000HR                   1289
#define IDC_LOWSC                       1290
#define IDC_LOWERC                      1291
#define IDC_MEDSC                       1292
#define IDC_MEDERC                      1293
#define IDC_HIGHSC                      1294
#define IDC_HIGHERC                     1295
#define IDC_EXTSC                       1296
#define IDC_EXTERC                      1297
#define IDC_CLASSAPPLY                  1298
#define IDC_TEXTFIELD                   1300
#define IDC_EDITFIRES                   1301
#define IDC_EDITRH                      1301
#define IDC_MM1                         1302
#define IDC_VIEWUNITS                   1302
#define IDC_EDITACRES                   1302
#define IDC_MM2                         1303
#define IDC_EDITSAMPLE                  1303
#define IDC_HM1                         1304
#define IDC_HM2                         1305
#define IDC_EM1                         1306
#define IDC_EM2                         1307
#define IDC_BKGRNDBUTTON                1312
#define IDC_EDITRYVAL                   1313
#define IDC_DATATABLEDB1                1314
#define IDC_SORTNAME                    1315
#define IDC_SORTDATE                    1316
#define IDC_SORTACRES                   1317
#define IDC_FIREVALUE                   1318
#define IDC_VIEWLOGBUTTON               1319
#define IDC_TEXTAREA                    1320
#define IDC_NODUPCHECK                  1322
#define IDC_DUPCHECK                    1323
#define IDC_STATIONS                    1324
#define IDC_RICHEDIT1                   1325
#define IDC_PRINTBUTTON                 1326
#define IDC_SAVEBUTTON                  1327
#define IDC_DATAYEARS                   1328
#define IDC_DELETEBUTTON                1329
#define IDC_DATATABLEDB2                1330
#define IDC_PVDATE21                    1331
#define IDC_ADDDAY                      1332
#define IDC_REPORT                      1333
#define IDC_GRAPH                       1334
#define IDC_REMOVE                      1335
#define IDC_OPTIONS                     1336
#define IDC_CALCULATE                   1337
#define IDC_OUTPUTLIST                  1338
#define IDC_BLANK                       1339
#define IDC_SAME                        1340
#define IDC_PERCENTILES                 1341
#define IDC_LINEWIDTH                   1343
#define IDC_LINECOLOR                   1345
#define IDC_LINESTYLE                   1346
#define IDC_VARLIST                     1349
#define IDC_DOIBUTTON                   1350
#define IDC_FIELDSLIST                  1351
#define IDC_SELECTEDLIST                1353
#define IDC_UP                          1359
#define IDC_DOWN                        1360
#define IDC_TOP                         1361
#define IDC_START                       1361
#define IDC_BOTTOM                      1362
#define IDC_END                         1362
#define IDC_DATE2                       1363
#define IDC_DATE3                       1364
#define IDC_DATE4                       1365
#define IDC_DATE5                       1366
#define IDC_TIME1                       1367
#define IDC_TIME2                       1368
#define IDC_CUSTOM                      1369
#define IDC_ALLFIRES                    1369
#define IDC_CUSTSTATIC                  1370
#define IDC_LIGHTNING                   1370
#define IDC_AVAILSTATIC                 1371
#define IDC_CUSTSTATIC2                 1371
#define IDC_SELECTSTATIC                1372
#define IDC_CUSTSTATIC3                 1372
#define IDC_DELIMSTATIC                 1373
#define IDC_DATESTATIC                  1374
#define IDC_TIMESTATIC                  1375
#define IDC_SPACE                       1376
#define IDC_TIMESTATIC2                 1376
#define IDC_COMMA                       1377
#define IDC_DATE1                       1378
#define IDC_CUSTSTATIC4                 1379
#define IDC_EXTRA                       1382
#define IDC_TYPE_14                     1384
#define IDC_TYPE_21                     1385
#define IDC_NOTIME                      1386
#define IDC_TYPE_15                     1386
#define IDC_HUMAN                       1387
#define IDC_TYPE_16                     1387
#define IDC_TYPE_19                     1388
#define IDC_TYPE_25                     1389
#define IDC_WTR3FILEBUTTON              1390
#define IDC_TYPE_26                     1390
#define IDC_WTR3EDIT                    1391
#define IDC_TYPE_37                     1391
#define IDC_WTR4EDIT                    1392
#define IDC_WTR4FILEBUTTON              1393
#define IDC_WNDEDIT                     1394
#define IDC_WNDFILEBUTTON               1395
#define IDC_STATIC1                     1396
#define IDC_STATIC2                     1397
#define IDC_STATIC3                     1398
#define IDC_SAVE                        1399
#define IDC_PRINT                       1400
#define IDC_NFDRSCTRL1                  1400
#define IDC_TRASH                       1401
#define IDC_PRINT2                      1403
#define IDC_MERGESTRING                 1408
#define IDC_NUMFIRES                    1409
#define IDC_NUMLARGEFIRES               1410
#define IDC_LFDNUM                      1411
#define IDC_PVNUMERIC3                  1412
#define IDC_READ_STATION                1413
#define IDC_SINGLE_STATION              1414
#define IDC_COMBO_STATION               1415
#define IDC_NEWVAR                      1417
#define IDC_DELETEVAR                   1418
#define IDC_FILENAME                    1419
#define IDC_FILEBUTTON                  1420
#define IDC_IMPORTBUTTON                1421
#define IDC_NUMPERCLASS                 1422
#define IDC_ACRES                       1423
#define IDC_RESPONSIBLEAGENCY           1424
#define IDC_DATETIMEPICKER1             1426
#define IDC_SPINSTART                   1427
#define IDC_DATETIMEPICKER2             1427
#define IDC_SPINEND                     1428
#define IDC_EDITCP                      1428
#define IDC_SPINYEAR                    1428
#define IDC_SPIN_KBDI_THRESHOLD         1428
#define IDC_SPINCP                      1429
#define IDC_DATETIMEPICKER3             1429
#define IDC_SPINGWIDTH                  1430
#define IDC_EDITYEAR1                   1430
#define IDC_DATETIMEPICKER4             1430
#define IDC_EDITGWIDTH                  1431
#define IDC_SPINYEAR1                   1431
#define IDC_EDITGHEIGHT                 1432
#define IDC_EDITYEAR2                   1432
#define IDC_EDITAVG                     1432
#define IDC_SPINGHEIGHT                 1433
#define IDC_SPINYEAR2                   1433
#define IDC_SPINAVG                     1433
#define IDC_EDITPHEIGHT                 1434
#define IDC_EDITWIND                    1434
#define IDC_EDITMINS                    1434
#define IDC_SPINFIRES                   1434
#define IDC_SPINPHEIGHT                 1435
#define IDC_SPINWIND                    1435
#define IDC_SPINMINS                    1435
#define IDC_SPINACRES                   1435
#define IDC_EDITWIDTH                   1435
#define IDC_EDITPWIDTH                  1436
#define IDC_EDITMAXS                    1436
#define IDC_SPINWIDTH                   1436
#define IDC_SPINSAMPLE                  1436
#define IDC_SPINPWIDTH                  1437
#define IDC_SPINRH                      1437
#define IDC_SPINMAXS                    1437
#define IDC_SPIN_1HR_DRIZZLE            1437
#define IDC_EDITTEMP                    1438
#define IDC_EDITCP1                     1438
#define IDC_SPIN_1HR_RAIN               1438
#define IDC_SPINTEMP                    1439
#define IDC_SPINCP1                     1439
#define IDC_SPIN_1HR_SHOWERS            1439
#define IDC_EDITLIVE_FM                 1440
#define IDC_EDITCP2                     1440
#define IDC_SPINWID                     1440
#define IDC_SPIN_3HR_AMT                1440
#define IDC_SPINLIVE_FM                 1441
#define IDC_SPINCP2                     1441
#define IDC_SPIN_24HR_AMT               1441
#define IDC_EDIT_FREG                   1442
#define IDC_SPIN_FREG                   1443
#define IDC_EDITWID                     1444
#define IDC_EDIT_LREG                   1444
#define IDC_EDITSTART                   1444
#define IDC_SPIN_LREG                   1445
#define IDC_EDITEND                     1445
#define IDC_EDITLAT                     1445
#define IDC_EDIT_FUNIT                  1446
#define IDC_SPINLAT                     1446
#define IDC_EDITYEAR                    1446
#define IDC_SPIN_FUNIT                  1447
#define IDC_EDITLONG                    1447
#define IDC_EDIT_LUNIT                  1448
#define IDC_SPINLONG                    1448
#define IDC_SPIN_LUNIT                  1449
#define IDC_EDITELEV                    1449
#define IDC_EDIT_FSUBUNIT               1450
#define IDC_SPINELEV                    1450
#define IDC_SPIN_FSUBUNIT               1451
#define IDC_EDITPRECIP                  1451
#define IDC_EDIT_LSUBUNIT               1452
#define IDC_SPINPRECIP                  1452
#define IDC_SPIN_LSUBUNIT               1453
#define IDC_EDITFM1000                  1453
#define IDC_EDIT_YEAR                   1454
#define IDC_SPINFM1000                  1454
#define IDC_SPIN_YEAR                   1455
#define IDC_ANNUALFILTER                1455
#define IDC_EDITFFMC                    1455
#define IDC_EDIT_KBDI_THRESHOLD         1455
#define IDC_EDIT_MONTH                  1456
#define IDC_ADDROW                      1456
#define IDC_ADDTL                       1456
#define IDC_SPINFFMC                    1456
#define IDC_SPIN_MONTH                  1457
#define IDC_REMOVEROW                   1457
#define IDC_EDITDMC                     1457
#define IDC_EDIT_DAY                    1458
#define IDC_EDIT_RUN_ID                 1458
#define IDC_SPINDMC                     1458
#define IDC_SPIN_DAY                    1459
#define IDC_EDIT_RUN_STATION            1459
#define IDC_EDITDC                      1459
#define IDC_EDIT_FFNUM                  1460
#define IDC_RUNID                       1460
#define IDC_EDIT_RUN_DESCRIPTION        1460
#define IDC_SPINDC                      1460
#define IDC_SPIN_FFNUM                  1461
#define IDC_STATIC1_DELIMITER           1461
#define IDC_EDIT_LFNUM                  1462
#define IDC_RADIO_DELIMITER_SPACE       1462
#define IDC_SPIN_LFNUM                  1463
#define IDC_RADIO_DELIMTER_TABS         1463
#define IDC_EDIT_FACRES                 1464
#define IDC_RADIO_DELIMITER_COMMA       1464
#define IDC_SPIN_FACRES                 1465
#define IDC_RADIO_DELIMITER_COLON       1465
#define IDC_RADIO_DELIMITER_PIPE        1465
#define IDC_EDIT_LACRES                 1466
#define IDC_RADIO_DELIMITER_SEMICOLON   1466
#define IDC_SPIN_LACRES                 1467
#define IDC_RADIO_DELIMITER_TABS        1467
#define IDC_EDIT_CAUSE                  1468
#define IDC_AUTOSAVE_GRAPH              1468
#define IDC_SPIN_CAUSE                  1469
#define IDC_FILETYPE                    1469
#define IDC_EDIT_FNAME                  1470
#define IDC_EDITLOCATION                1470
#define IDC_SPIN_FNAME                  1471
#define IDC_BROWSE_FOLDER               1471
#define IDC_EDIT_LNAME                  1472
#define IDC_BATCH_DESCRIPTION           1472
#define IDC_SPIN_LNAME                  1473
#define IDC_EDIT_BATCH_DESCRIPTION      1473
#define IDBATCHRUN                      1474
#define IDC_BATCHRUN                    1474
#define IDBATCHEDIT                     1475
#define IDC_BATCHEDIT                   1475
#define IDC_TAB1                        1475
#define IDBATCHDELETE                   1476
#define IDC_BATCHDELETE                 1476
#define IDC_SCHEME_NUM                  1476
#define IDC_SCHEME_LRU                  1477
#define IDC_BATCHEDIT2                  1477
#define IDC_BATCHNEW                    1477
#define IDC_SCHEME_PERIODIC             1478
#define IDC_BATCHRUN2                   1478
#define IDC_BATCHRUNAUTOSAVE            1478
#define IDC_RUNS_NUMBER                 1479
#define IDC_PERIODIC_SELECT             1480
#define IDC_STATIC69                    1481
#define IDC_SCHEME_NONE                 1482
#define IDC_EDIT_RUN_DESC               1482
#define IDC_STATIC70                    1483
#define IDC_RUNS_NUMBER2                1484
#define IDC_PURGE                       1486
#define IDC_PROMPT_DESC                 1487
#define IDC_RUNSAVE_DESCRIPTION         1488
#define IDC_WIND_ROSE_GRAPH             1489
#define IDC_WIND_ROSE_PERCENTAGE        1490
#define IDC_WIND_ROSE_WINDS             1491
#define IDC_RICHEDIT21                  1491
#define IDC_SPIN_LOW1HR                 1492
#define IDC_SPIN_LOW10HR                1493
#define IDC_NFDRS4CTRL1                 1493
#define IDC_SPIN_LOW100HR               1494
#define IDC_EXPORT                      1494
#define IDC_SPIN_LOWHERB                1495
#define IDC_IMPORT_WX                   1495
#define IDC_SPIN_LOWWOODY               1496
#define IDC_IMPORT_FIRE                 1496
#define IDC_SPIN_LOW20                  1497
#define IDC_1H                          1497
#define IDC_SPIN_LOW1000HR              1498
#define IDC_10H                         1498
#define IDC_EDITCALM                    1498
#define IDC_SPIN_LOW1HR2                1499
#define IDC_100H                        1499
#define IDC_SPINCALM                    1499
#define IDC_SPIN_LOW10HR2               1500
#define IDC_100H2                       1500
#define IDC_1000H                       1500
#define IDC_IPADDRESS1                  1500
#define IDC_SHOWALLSTATIONS             1500
#define IDC_EDIT_BIN_SIZE               1500
#define IDC_SPIN_LOW100HR2              1501
#define IDC_CUSTOMINITNEW               1501
#define IDC_SPIN_BIN_SIZE               1501
#define IDC_SPIN_LOWHERB2               1502
#define IDC_CUSTOMINITEDIT              1502
#define IDC_EDIT_MAX_SPEED              1502
#define IDC_SPIN_LOWWOODY2              1503
#define IDC_CUSTOMINITDELETE            1503
#define IDC_SPIN_MAX_SPEED              1503
#define IDC_SPIN_LOW21                  1504
#define IDC_CUSTOMINIT_YEAR             1504
#define IDC_SPIN_LOW1000HR2             1505
#define IDC_CUSTOMINITCHECK             1505
#define IDC_SPIN_LOW1HR3                1506
#define IDC_INIT_STATION                1506
#define IDC_SPIN_LOW10HR3               1507
#define IDC_BUTTON_SELECT_ALL           1507
#define IDC_SPIN_LOW100HR3              1508
#define IDC_BUTTON_CLEAR_ALL            1508
#define IDC_SPIN_LOWHERB3               1509
#define IDC_SPIN_LOWWOODY3              1510
#define IDC_SPIN_LOW22                  1511
#define IDC_DUP_REJECT                  1511
#define IDC_SPIN_LOW1000HR3             1512
#define IDC_DUP_OVERWRITE               1512
#define IDC_SPIN_LOW1HR4                1513
#define IDC_USESTATIONID                1513
#define IDC_SPIN_LOW10HR4               1514
#define IDC_USEOBSTYPE                  1514
#define IDC_SPIN_LOW100HR4              1515
#define IDC_OBSTYPE                     1515
#define IDC_SPIN_LOWHERB4               1516
#define IDC_USEOBSTIME                  1516
#define IDC_SPIN_LOWWOODY4              1517
#define IDC_DATETIMEPICKER_OBSTIME      1517
#define IDC_SPIN_LOW23                  1518
#define IDC_SORT_COMBO                  1518
#define IDC_SPIN_LOW1000HR4             1519
#define IDC_MANUAL_MAINTENANCE          1519
#define IDC_WINDS_0_4                   1520
#define IDC_WINDS_4_8                   1521
#define IDC_BUTTON_DEFAULTS             1521
#define IDC_WINDS_8_12                  1522
#define IDC_RADIO_VPD_MAX               1522
#define IDC_WINDS_12_16                 1523
#define IDC_RADIO_VPD_AVG               1523
#define IDC_WINDS_16_20                 1524
#define IDC_BUTTON_DEFAULTS_STORED      1524
#define IDC_WINDS_20_0                  1525
#define IDC_EDIT_TMINMIN                1525
#define IDC_WINDROSE_SPLIT              1526
#define IDC_SPIN_TMINMIN                1526
#define IDC_EDIT_TMINMAX                1527
#define IDC_SPIN_TMINMAX                1528
#define IDC_BUTTON_DELETE               1528
#define IDC_EDIT_VPDMIN                 1529
#define IDC_SPIN_VPDMIN                 1530
#define IDC_EDIT_VPDMAX                 1531
#define IDC_SPIN_VPDMAX                 1532
#define IDC_EDIT_DAYLENMIN              1533
#define IDC_SPIN_DAYLENMIN              1534
#define IDC_EDIT_DAYLENMAX              1535
#define IDC_SPIN_DAYLENMAX              1536
#define IDC_EDIT_DAYS_AVG               1537
#define IDC_SPIN_DAYS_AVG               1538
#define IDC_BUTTON_DEFAULTS_SAVE        1539
#define IDC_BUTTON_SETWEIGHTS           1540
#define IDC_EDIT_DAYS_PRECIP            1540
#define IDC_NEW_STATION                 1541
#define IDC_SPIN_DAYS_PRECIP            1541
#define IDC_BUTTON_NEW                  1542
#define IDC_EDIT_PRECIP_MIN             1542
#define IDC_BUTTON_EDIT                 1543
#define IDC_EDIT_MAXGSI                 1543
#define IDC_SPIN_PRECIP_MIN             1543
#define IDC_SPIN_MAXGSI                 1544
#define IDC_EDIT_PRECIP_MAX             1544
#define IDC_EDIT_GREENUP                1545
#define IDC_SPIN_PRECIP_MAX             1545
#define IDC_EDIT_NAME                   1546
#define IDC_SPIN_GREENUP                1546
#define IDC_DATETIMEPICKER_STARTDAY     1547
#define IDC_EDIT_MAXHERBFM              1547
#define IDC_EDIT_STARTYEAR              1548
#define IDC_SPIN_MAXHERBFM              1548
#define IDC_SPIN_PRECIP_MAX3            1548
#define IDC_SPIN_STARTYEAR              1549
#define IDC_EDIT_MINHERBFM              1549
#define IDC_EDIT_ENDYEAR                1550
#define IDC_SPIN_MINHERBFM              1550
#define IDC_SPIN_ENDYEAR                1551
#define IDC_SPIN_PRECIP_MIN2            1551
#define IDC_BUTTON_APPLY                1552
#define IDC_EDIT_PRECIP_MAX2            1552
#define IDC_SPIN_PRECIP_MAX2            1553
#define IDC_BUTTON_SAVE                 1556
#define IDC_BUTTON_IMPORT               1557
#define IDC_RICHEDIT21_COMMENT          1558
#define IDC_BUTTON_COPY                 1559
#define IDC_COMBO_TERMS                 1560
#define IDC_BUTTON_ADD_TO_NEW           1561
#define IDC_BUTTON_ADD_EXISTING         1562
#define IDC_BUTTON_APPEND               1563
#define IDC_BUTTON_INSERT               1564
#define IDC_BUTTON_ASCENDING            1566
#define IDC_BUTTON_DESCENDING           1567
#define IDC_BUTTON_LOAD_DEFAULTS        1568
#define IDC_BUTTON_SET_DEFAULTS         1569
#define IDC_BUTTON_PROBABILITIES        1569
#define IDC_BUTTON_SET_DEFAULT          1570
#define IDC_STATIC_TABLELABEL           1571
#define IDC_FLAMMAPFARSITE_STREAM       1572
#define IDC_EDIT_PCNT_CLEAR             1574
#define IDC_SPIN_PCNT_CLEAR             1575
#define IDC_EDIT_PCNT_SCATTERED         1576
#define IDC_SPIN_PCNT_SCATTERED         1577
#define IDC_EDIT_PCNT_BROKEN            1578
#define IDC_SPIN_PCNT_BROKEN            1579
#define IDC_EDIT_3HR_DUR                1580
#define IDC_SPIN_3HR_DUR                1581
#define IDC_EDIT_24HR_DUR               1582
#define IDC_SPIN_24HR_DUR               1583
#define IDC_EDIT_1HR_DRIZZLE            1584
#define IDC_EDIT_1HR_RAIN               1585
#define IDC_BUTTON_SOW_THRESHOLDS       1585
#define IDC_EDIT_1HR_SHOWERS            1586
#define IDC_BUTTON_SOW_WETFLAG_OPTIONS  1586
#define IDC_RADIO_USE_WHEN_SOW_NULL     1586
#define IDC_EDIT_3HR_AMT                1587
#define IDC_RADIO_ONLY_SR_SOW           1587
#define IDC_BUTTON_SOW_WETFLAG_OPTIONS2 1587
#define IDC_BUTTON_RECALC_SOW_WETFLAG   1587
#define IDC_EDIT_24HR_AMT               1588
#define IDC_RADIO_USE_WHEN_WETFLAG_NULL 1588
#define IDC_RADIO_ONLY_EST_WET_FLAG     1589
#define IDC_RADIO_NEVER_SR_SOW          1590
#define IDC_RADIO_NEVER_EST_WET_FLAG    1591
#define IDC_CHECK_MULTIPLE_FIRE_DAY     1592
#define IDC_EDIT_NESDIS_ID              1595
#define IDC_COMBO_REG_SCHED_OBS_HOUR    1596
#define IDC_EDIT_WRCC_ID                1597
#define IDC_BUTTON_EXPORT               1598
#define IDC_PROGCTRL1                   1599
#define IDC_PROGRESS                    1599
#define IDC_PDF                         1600
#define IDC_DL_EXPORT                   1601
#define IDC_PDF1                        1602
#define IDC_HTML                        1604
#define IDC_STATION_WIMS                1606
#define IDC_STATION_WRCC                1607
#define IDC_EXPLORER2                   1608
#define IDC_WRCC_MESSAGE                1609
#define IDC_VERSION_STRING              1610
#define IDC_CAUSE_1                     1611
#define IDC_CAUSE_2                     1612
#define IDC_CAUSE_3                     1613
#define IDC_CAUSE_4                     1614
#define IDC_CAUSE_5                     1615
#define IDC_CAUSE_6                     1616
#define IDC_CAUSE_7                     1617
#define IDC_CAUSE_8                     1618
#define IDC_CAUSE_9                     1619
#define IDC_CAUSE_10                    1620
#define IDC_NASF_CSV                    1621
#define IDC_WXSFILEBUTTON               1622
#define IDC_WXSEDIT                     1623
#define IDC_EDIT_MAXSC_V                1624
#define IDC_SPIN_MAXSC_V                1625
#define IDC_EDIT_MAXSC_W                1626
#define IDC_CHECK_FORCE_RECOMPUTE       1626
#define IDC_SPIN_MAXSC_W                1627
#define IDC_COMBO_SNOWFLAG              1627
#define IDC_EDIT_MAXSC_X                1628
#define IDC_SPIN_MAXSC_X                1629
#define IDC_SPIN_SYEAR                  1629
#define IDC_EDIT_MAXSC_Y                1630
#define IDC_SPIN_EYEAR                  1630
#define IDC_SPIN_MAXSC_Y                1631
#define IDC_SPIN_SDAY                   1631
#define IDC_EDIT_MAXSC_Z                1632
#define IDC_SPIN_EDAY                   1632
#define IDC_SPIN_MAXSC_Z                1633
#define IDC_COMBO_OBS_HOUR              1633
#define IDC_RADIO_HOURLY_PRECIP         1634
#define IDC_RADIO_DAILY_PRECIP          1635
#define IDC_CHECK_WEIBULL               1636
#define IDC_RADIO_ABSOLUTE_STATIC       1637
#define IDC_RADIO_USE_MAX               1638
#define IDC_RADIO_FW21                  1639
#define IDC_COMBO_TIMEZONE              1640
#define IDC_COMBO_VPD_USAGE             1641
#define IDC_RADIO_OFFSET                1642
#define IDC_EDIT_DEST_FILE              1644
#define IDC_BUTTON_DEST_FILE            1645
#define IDC_COMBO_TIME_FORMAT           1646
#define ID_CLIMATOLOGY                  32771
#define ID_SIGS                         32772
#define ID_DATA_IMPORT                  32773
#define ID_DATA_EXPORT                  32774
#define ID_DATA_VALIDATION              32775
#define ID_DATA_REPAIR                  32776
#define ID_WINDOW_CLOSEALL_REPORTSANDGRAPHS 32779
#define ID_WINDOW_CLOSEALL_WINDOWS      32780
#define ID_CUSTOM_CLOSE                 32781
#define ID_FILE_AUXILARYMODELS_CANADIAN 32783
#define ID_FILE_OVERLAY                 32784
#define ID_RERAP                        32785
#define ID_OPTIONS_GRAPHTYPE_STATISTICALBARS 32787
#define ID_OPTIONS_GRAPHTYPE_LINEATAVERAGE 32788
#define ID_OPTIONS_OVERLAYS             32789
#define ID_OPTIONS_AUXILIARYMODELS_CANADIAN 32790
#define ID_OPTIONS_COLUMNS_DAILYFREQUENCIES 32791
#define ID_OPTIONS_COLUMNS_PERIODMINIMUMS 32792
#define ID_OPTIONS_COLUMNS_PERIODMAXIMUMS 32793
#define ID_OPTIONS_GRAPHSETUP           32794
#define ID_OPTIONS_COLUMNS_DATACOUNT    32795
#define ID_WEATHER_POCKETCARD           32796
#define ID_WEATHER_SEASONREPORTS_PERSISTENCEPROBABILITY 32797
#define ID_WEATHER_SEASONREPORTS_SEVERITYLIST 32798
#define ID_WEATHER_SEASONREPORTS_SEVERITYSUMMARY 32799
#define ID_WEATHER_SEASONREPORTS_PROBABILITYANALYSIS 32800
#define ID_FIRES_FIREBUSINESS           32801
#define ID_FIRES_FIREANALYSIS           32802
#define ID_HELP_CONTENTS                32803
#define ID_HELP_SEARCH                  32804
#define ID_WEATHER_SEASONREPORTS_DAILYLISTING 32815
#define ID_DATA_WEATHEROBSERVATIONS     32816
#define ID_DATA_STATIONS                32817
#define ID_FIRES_ASSOCIATIONS           32818
#define ID_OPTIONS_DISPLAYOPTONS        32819
#define ID_FIRES_SUMMARY_WORKINGSET     32824
#define ID_FILE_PRINT_PRINTGRAPH        32825
#define ID_FILE_SAVE_GRAPH              32827
#define ID_DATA_AGENCIES                32828
#define ID_FILE_PRINT1                  32829
#define ID_WEATHER_WINDS                32830
#define ID_DATA_COMPACT                 32831
#define ID_FILE_NEW_FFP                 32832
#define ID_FILE_SAVE_AS_FFP             32833
#define ID_WEATHER_EVENTLOCATOR         32834
#define ID_FILE_SAVE_PERCENTILESGRAPH   32842
#define ID_FILE_SAVE_BARGRAPH           32843
#define ID_DECISIONPOINTS               32844
#define ID_DECISIONPOINT                32845
#define ID_FILE_PRINT_GRAPH_PERCENTILES 32846
#define ID_FILE_PRINT_GRAPH_PROBABILITIES 32847
#define ID_FILE_PRINT_GRAPH_CLASSPERCENTAGES 32848
#define ID_FILE_SAVE_GRAPH_PERCENTILES  32849
#define ID_FILE_SAVE_GRAPH_PROBABILITIES 32850
#define ID_FILE_SAVE_GRAPH_CLASSPERCENTAGES 32851
#define ID_WEATHER_FORECASTING          32852
#define ID_WEATHER_NFDRSCALCULATOR      32854
#define ID_WEATHER_DIURNALANALYSIS      32856
#define ID_WEATHER_VIEWOBSERVATIONS_DAILY 32857
#define ID_WEATHER_VIEWOBSERVATIONS_HOURLY 32858
#define ID_WEATHER_VIEWOBSERVATIONS_ALL 32859
#define ID_FILE_PRINT_GRAPH             32860
#define ID_WEATHER_DIURNAL_HOURLYLISTING 32862
#define ID_WEATHER_DIURNAL_GRAPH        32863
#define ID_SORT_SORTASCENDING           32864
#define ID_SORT_SORTDESCENDING          32865
#define ID_WEATHER_HOURLYDATAANALYSIS_FARSITEEXPORTS 32866
#define ID_VIEW_DISCARDEDFIRES          32867
#define ID_TOOLS_CLASSDEFINITIONS       32868
#define ID_FILE_PRINT_REPORT            32869
#define ID_EXPORT_PERCENTILES           32870
#define ID_OPTIONS_MERGE_DRYBULBTEMP    32873
#define ID_OPTIONS_MERGE_MEANTEMP       32874
#define ID_OPTIONS_MERGE_MINTEMP        32875
#define ID_OPTIONS_MERGE_MAXTEMP        32876
#define ID_OPTIONS_MERGE_RH             32877
#define ID_OPTIONS_MERGE_MEANRH         32878
#define ID_OPTIONS_MERGE_MINRH          32879
#define ID_OPTIONS_MERGE_MAXRH          32880
#define ID_OPTIONS_MERGE_PRECIPAMOUNT   32881
#define ID_OPTIONS_MERGE_PRECIPDURATION 32882
#define ID_OPTIONS_MERGE                32883
#define ID_FILE_SAVE_REPORT             32884
#define ID_DATA_USERVARIABLES           32885
#define ID_DATA_USERVARIABLES_MANAGE    32886
#define ID_DATA_USERVARIABLES_IMPORTDATA 32887
#define ID_DATA_USERVARIABLES_VIEWOBSERVATIONS 32888
#define ID_FILE_SAVE_DIURNAL_REPORT     32889
#define ID_WEATHER_FPAANALYSIS          32890
#define ID_OPTIONS_RUN_RESTORE          32891
#define ID_OPTIONS_REPORTOPTIONS        32892
#define ID_Menu                         32893
#define ID_OPTIONS_VIEWHEADERINFO       32894
#define ID_FILE_EXPORTGRAPHDATA         32896
#define ID_BATCH_CREATENEWBATCH         32900
#define ID_Menu32901                    32901
#define ID_BATCH_MANAGEBATCHLIST        32902
#define ID_OPTIONS_BATCH                32903
#define ID_FILE_CLOSE32904              32904
#define ID_BATCH_SAVEDRUNMAINTENANCE    32905
#define ID_WEATHER_FLAMMAPEXPORTS       32906
#define ID_WEATHER_WINDROSE             32907
#define ID_BATCH_INTERACTIVE            32909
#define ID_QUICKBATCH_WORKINGSET        32911
#define ID_SAVE_GRAPH                   32915
#define ID_SAVE_PERCENTILEGRAPH         32916
#define ID_NELSON                       32921
#define ID_QB_GRAPH_OPTIONS             32922
#define ID_QUICK_OVERLAYS               32923
#define ID_BUTTON32924                  32924
#define ID_BUTTON_FIRE_ASSOC            32925
#define ID_BUTTON_FIRE_OPTIONS          32926
#define ID_QB_CLOSE                     32928
#define ID_QUICK_SAVE                   32929
#define ID_QUICK_PRINT                  32930
#define ID_QUICK_PROPERTIES             32932
#define ID_WEATHER_CUSTOMYEARLYINITS    32933
#define ID_CUSTOMYEARLYINITS            32934
#define ID_NELSONDEADFUELMOISTURES_HOURLYVALUES 32935
#define ID_NELSONDEADFUELMOISTURES_COMPAREWITHDAILYNFDRS 32936
#define ID_NELSON2                      32937
#define ID_HOURLY_EVENTLOCATOR          32938
#define ID_WEATHER_HOURLY_EVENTLOCATOR  32939
#define ID_BATCH_ENABLERUNSAVING        32940
#define ID_OPTIONS_LFISETTINGS          32941
#define ID_DATA_ADDTOCANDIDATESLIST     32943
#define ID_WEATHER_FIREBUSINESSCANDIDATES 32945
#define ID_TREE_EDIT                    32947
#define ID_TREE_WORKINGSET              32948
#define ID__FIREASSOCIATIONS            32949
#define ID_TREE_FIREASSOCIATIONS        32950
#define ID_DATA_EDITSIG                 32951
#define ID_OPTIONS_VIEWCLASSDEFINITIONS 32953
#define ID_WEATHER_TERM                 32954
#define ID_OPTIONS_TERM                 32955
#define ID_TERM_EDIT                    32956
#define ID_TERM_NEWTERM                 32957
#define ID_TERM_NEW                     32958
#define ID_TERM_COPY                    32959
#define ID_TERM_GENERAL                 32964
#define ID_TERM_WORKINGSET              32965
#define ID_NELSONDEADFUELMOISTURES_FIRESANALYSIS 32966
#define ID_FIRESANALYSIS_ALLNELSONMOISTURES 32967
#define ID_FIRESANALYSIS_1AND10HOURMOISTURES 32968
#define ID_COMPAREWITHDAILYNFDRS_ALLNELSONMOISTURES 32969
#define ID_COMPAREWITHDAILYNFDRS_1AND10HOURMOISTURES 32970
#define ID_DATA_PRINT                   32971
#define ID_VIEW_FSIMLARGEFIREDISTFILE   32971
#define ID_DATA_DELETERECORDS           32972
#define ID_FILE_EXITFIREFAMILYPLUS      32979
#define ID_VIEW_FIREDAY                 32980
#define ID_VIEW_LARGEFIREDAY            32981
#define ID_VIEW_MULTIPLEFIREDAY         32982
#define ID_HOURLYDATAANALYSIS_CALCULATEDSOW 32983
#define ID_CALCULATEDSOW_THRESHOLDS     32984
#define ID_CALCULATEDSOW_OPTIONS        32985
#define ID_CALCULATEDSOW_RECALCULATESR  32986
#define ID_LFIOPTIONS_CURRENTSIG        32987
#define ID_LFIOPTIONS_DEFAULTS          32988
#define ID_BUTTON32989                  32989
#define ID_OPTIONS_BATCH2               32990
#define ID_VARSORT                      32991
#define ID_TERM_EXPORT                  32992
#define ID_OPTIONS_CAUSECODES           32993
#define ID_OPTIONS_CAUSECODES2          32994
#define ID_CAUSE_MORE                   32995
#define ID_VARSORT2                     32996
#define ID_VIEWOBSERVATIONS_NFDRS2016PRECALCS 32997
#define ID_VIEWOBSERVATIONS_NFDRS2016_INPUTS 32998
#define ID_DATA_UTILITIES               32999
#define ID_UTILITIES_SNOWFLAG           33000
#define ID_SNOWFLAG_SETBYFILTER         33001
#define ID_SNOWFLAG_FILLHOURLYFROMDAILY 33002
#define ID_UTILITIES_SETDAILYOBS        33003
#define ID_INDICATOR_X                  61191
#define ID_INDICATOR_Y                  61192
#define ID_INDICATOR_XPROMPT            61204
#define ID_INDICATOR_YPROMPT            61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        429
#define _APS_NEXT_COMMAND_VALUE         33004
#define _APS_NEXT_CONTROL_VALUE         1647
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
